# Inserts a blank line between shell prompts
add_newline = false

[aws]
disabled=true

[azure]
disabled=true

[battery]
disabled=true

[buf]
disabled=true

[bun]
disabled=true

[c]
disabled=true

[character]
success_symbol = '[➜](bold yellow)'
error_symbol = '[✗](bold red)'
disabled=false

[cmake]
disabled=true

[cobol]
disabled=true

[cmd_duration]
disabled=true

[conda]
disabled=true

[container]
disabled=true

[crystal]
disabled=true

[daml]
disabled=true

[dart]
disabled=true

[deno]
disabled=true

[directory]
disabled=false

[docker_context]
disabled=true

[dotnet]
disabled=true

[elixir]
disabled=true

[elm]
disabled=true

[env_var]
disabled=true

[erlang]
disabled=true

[fill]
disabled=true

[gcloud]
disabled=true

[git_branch]
disabled=false

[git_commit]
disabled=false

[git_state]
disabled=false

[git_metrics]
disabled=false

[git_status]
disabled=false

[golang]
disabled=true

[guix_shell]
disabled=true

[haskell]
disabled=true

[haxe]
disabled=true

[helm]
disabled=true

[hostname]
disabled=false

[java]
disabled=true

[jobs]
disabled=false

[julia]
disabled=true

[kotlin]
disabled=true

[kubernetes]
disabled=true

[line_break]
disabled=false

[localip]
disabled=true

[lua]
disabled=true

[memory_usage]
disabled=true

[meson]
disabled=true

[hg_branch]
disabled=true

[nim]
disabled=true

[nix_shell]
disabled=true

[nodejs]
disabled=true

[ocaml]
disabled=true

[opa]
disabled=true

[openstack]
disabled=true

[os]
disabled=true

[package]
disabled=true

[perl]
disabled=true

[php]
disabled=true

[pulumi]
disabled=true

[purescript]
disabled=true

[python]
disabled=true

[rlang]
disabled=true

[raku]
disabled=true

[red]
disabled=true

[ruby]
disabled=true

[rust]
disabled=true

[scala]
disabled=true

[shell]
disabled=true

[shlvl]
disabled=true

[singularity]
disabled=true

[spack]
disabled=true

[status]
disabled=true

[sudo]
disabled=true

[swift]
disabled=true

[terraform]
disabled=true

[time]
disabled=true

[username]
disabled=true

[vagrant]
disabled=true

[vlang]
disabled=true

[vcsh]
disabled=true

[zig]
disabled=true
